class ContextType:
    EXPIRY_DAY_MORNING = "EXPIRY_DAY_MORNING"
    EXPIRY_DAY_AFTERNOON = "EXPIRY_DAY_AFTERNOON"
    PRE_EXPIRY_DAY = "PRE_EXPIRY_DAY"
    GAP_UP_CONTINUATION = "GAP_UP_CONTINUATION"
    GAP_DOWN_CONTINUATION = "GAP_DOWN_CONTINUATION"
    GAP_FADE = "GAP_FADE"
    HIGH_VIX_DAY = "HIGH_VIX_DAY"
    LOW_VIX_TRENDING = "LOW_VIX_TRENDING"
    INSIDE_DAY_OPENING = "INSIDE_DAY_OPENING"
    TRENDING_MORNING = "TRENDING_MORNING"
    RANGING_CHOPPY = "RANGING_CHOPPY"
    NEWS_EVENT_DAY = "NEWS_EVENT_DAY"
    MONTHLY_EXPIRY_WEEK = "MONTHLY_EXPIRY_WEEK"
    POST_GAP_STABILIZING = "POST_GAP_STABILIZING"
    STALE_DATA_DAY = "STALE_DATA_DAY"
    NORMAL_TRADING_DAY = "NORMAL_TRADING_DAY"
    UNKNOWN = "UNKNOWN"

    @classmethod
    def all_types(cls) -> list[str]:
        return [
            cls.EXPIRY_DAY_MORNING,
            cls.EXPIRY_DAY_AFTERNOON,
            cls.PRE_EXPIRY_DAY,
            cls.GAP_UP_CONTINUATION,
            cls.GAP_DOWN_CONTINUATION,
            cls.GAP_FADE,
            cls.HIGH_VIX_DAY,
            cls.LOW_VIX_TRENDING,
            cls.INSIDE_DAY_OPENING,
            cls.TRENDING_MORNING,
            cls.RANGING_CHOPPY,
            cls.NEWS_EVENT_DAY,
            cls.MONTHLY_EXPIRY_WEEK,
            cls.POST_GAP_STABILIZING,
            cls.STALE_DATA_DAY,
            cls.NORMAL_TRADING_DAY,
            cls.UNKNOWN,
        ]
