class SetupName:
    PE_BREAKDOWN_CONTINUATION = "PE_BREAKDOWN_CONTINUATION"
    CE_BREAKOUT_CONTINUATION = "CE_BREAKOUT_CONTINUATION"
    PE_RETEST_CONTINUATION = "PE_RETEST_CONTINUATION"
    CE_RETEST_CONTINUATION = "CE_RETEST_CONTINUATION"
    PE_VWAP_REJECTION = "PE_VWAP_REJECTION"
    CE_VWAP_RECLAIM = "CE_VWAP_RECLAIM"
    PE_EXPIRY_MORNING_SCALP = "PE_EXPIRY_MORNING_SCALP"
    CE_EXPIRY_MORNING_SCALP = "CE_EXPIRY_MORNING_SCALP"
    PE_GAP_DOWN_CONTINUATION = "PE_GAP_DOWN_CONTINUATION"
    CE_GAP_UP_CONTINUATION = "CE_GAP_UP_CONTINUATION"
    NO_SETUP_FOUND = "NO_SETUP_FOUND"
    INSUFFICIENT_ENGINE_DATA = "INSUFFICIENT_ENGINE_DATA"

    @classmethod
    def directional_pe_setups(cls) -> list:
        return [
            cls.PE_BREAKDOWN_CONTINUATION,
            cls.PE_RETEST_CONTINUATION,
            cls.PE_VWAP_REJECTION,
            cls.PE_EXPIRY_MORNING_SCALP,
            cls.PE_GAP_DOWN_CONTINUATION,
        ]

    @classmethod
    def directional_ce_setups(cls) -> list:
        return [
            cls.CE_BREAKOUT_CONTINUATION,
            cls.CE_RETEST_CONTINUATION,
            cls.CE_VWAP_RECLAIM,
            cls.CE_EXPIRY_MORNING_SCALP,
            cls.CE_GAP_UP_CONTINUATION,
        ]
